tsml_estimator_evaluation/_wip/estimator_from_file/hivecote.py

This implements the functions _fit and _predict_proba.

HC from file version

---

tsml_eval/experiments/regression_experiments.py
tsml_eval/experiments/set_regressor.py
tsml_eval/sktime_estimators/regression/sklearn/__init__.py
tsml_eval/sktime_estimators/regression/sklearn/sklearn_regressor.py

standard sklearn classifiers. 3d to 2d is done in the class created for that. 
have to think about gridsearchcv though.

Standard classifiers david

---

.github/workflows/tests.yml
.pre-commit-config.yaml
pyproject.toml
tsml_eval/experiments/threaded_classification_experiments.py
tsml_eval/sktime_estimators/regression/sklearn/sklearn_regressor.py
tsml_eval/sktime_estimators/tests/test_check_estimator.py

Adds durations output and threading to pytest runs among other small changes to CI.

Add more info to test output

---

.github/workflows/tests.yml
pyproject.toml
tsml_eval/experiments/classification_experiments.py
tsml_eval/experiments/clustering_experiments.py
tsml_eval/experiments/distance_clustering_experiments.py
tsml_eval/experiments/regression_experiments.py
tsml_eval/sktime_estimators/classification/convolution_based/hydra.py
tsml_eval/sktime_estimators/classification/deep_learning/__init__.py
tsml_eval/sktime_estimators/classification/deep_learning/inception_time.py
tsml_eval/sktime_estimators/networks/inception_time.py
tsml_eval/sktime_estimators/tests/test_check_estimator.py

1. Fills out the InceptionTime ensemble methods to match the sktime-dl ensemble.
2. Adds both InceptionTime classifiers to the check_estimator tests
3. Isolates the deep learning dependencies somewhat

Inception time ensemble

---

tsml_eval/evaluation/metrics.py
tsml_eval/experiments/experiments.py

Simple function to return the Davies-Bouldin using a results file

davies_bouldin_score_from_file

---

.pre-commit-config.yaml
pyproject.toml

Latest sktime release is breaking tests, and we don't really want to use it anyway.
also bumps pre-commit to match scikit-time

`sktime` upper bound

---

tsml_eval/experiments/set_classifier.py

add InceptionTime/SingleInceptionTime distinction in set_classifier (to match set_regressor)

add InceptionTime ensemble to set_classifier

---

.pre-commit-config.yaml
requirements.txt
tsml_eval/evaluation/benchmark.py

Adds functions to benchmark runtime and memory usage of two estimators, as well as a helper function to perform a sequence of benchmarks with varying dataset sizes.
Also, updates one of the pre-commit repos (the previous version had compatibility issues).

Runtime and Memory Usage Benchmarking

---

tsml_eval/experiments/experiments.py
tsml_eval/experiments/regression_experiments.py
tsml_eval/experiments/set_regressor.py
tsml_eval/experiments/tests/test_regression.py

checkpoint paths included. 
look for _fit_time attribute in regressor class. If exists takes this value. (same behaviour for _test_time). 
Note that both parameters have to be introduced in the regressor class, as well as the lines for the checkpointing as it is not general across regressors. 
If needed, I can provide the code for knn (checkpoints the test output) or STR (checkpoints the shapelets).

Checkpoint

---

README.md
_uea_experiments/README.md
_uea_experiments/README.txt
docs/publications.md

Release for the 3 papers currently in publications. Clustering paper will be in v0.1.1.

Release v0.1.0

---

tsml_eval/experiments/set_classifier.py

use latest file structure for deep learning imports

[BUG] DL imports

---

tsml_eval/estimators/classification/convolution_based/_hydra_internal.py
tsml_eval/estimators/classification/convolution_based/hydra.py
tsml_eval/estimators/classification/feature_based/__init__.py
tsml_eval/estimators/classification/feature_based/quant.py

QUANT classifier using the code by Angus: https://github.com/angus924/quant/

[ENH] QUANT classifier

---

tsml_eval/_wip/experiments/collate_results.py
tsml_eval/_wip/results_summary.py

all in wip, just useful for me to store it somewhere so I dont reinvent the wheel  next tim

[ENH] some utility code for collating results

---

tsml_eval/estimators/classification/feature_based/grail.py
tsml_eval/testing/tests/test_test_utils.py
tsml_eval/utils/functions.py
tsml_eval/utils/memory_recorder.py
tsml_eval/utils/tests/test_functions.py

[BUG] GRAIL fix and some coverage

---

README.md
tsml_eval/estimators/clustering/consensus/tests/test_ivc.py

Comment out failing test

---

docs/publications.md
tsml_eval/evaluation/multiple_estimator_evaluation.py
tsml_eval/publications/y2023/tsc_bakeoff/set_bakeoff_classifier.py
tsml_eval/publications/y2023/tsc_bakeoff/tsc_bakeoff_2023.ipynb
tsml_eval/utils/publications.py

Updates and additional utilities for the bakeoff webpage

[ENH,DOC] Bakeoff webpage update

---

README.md
pyproject.toml
tsml_eval/__init__.py

[MNT] Release v0.3.0

---

.github/actions/numba_cache/action.yml
.github/workflows/issue_comment_edited.yml
.github/workflows/issue_comment_posted.yml
.github/workflows/periodic_github_maintenace.yml
.github/workflows/periodic_tests.yml
.github/workflows/pr_examples.yml
.github/workflows/pr_opened.yml
.github/workflows/pr_pre_commit.yml
.github/workflows/pr_pytest.yml
.github/workflows/precommit_autoupdate.yml
.github/workflows/release.yml
build_tools/comment_pr_labeler.py
build_tools/issue_assign.py
build_tools/pr_labeler.py
build_tools/pr_open_commenter.py
build_tools/run_examples.sh
tsml_eval/testing/_cicd_numba_caching.py
tsml_eval/testing/testing_config.py

[MNT] Update workflows

---

.github/workflows/periodic_tests.yml

Missing an input for the periodic example tests.

[MNT] Another workflow fix

---

.github/workflows/pr_pytest.yml
build_tools/comment_pr_labeler.py
build_tools/pr_open_commenter.py
docs/api.md
tsml_eval/experiments/__init__.py
tsml_eval/experiments/cross_validation.py
tsml_eval/experiments/experiments.py
tsml_eval/experiments/tests/test_cross_validation.py
tsml_eval/utils/experiments.py

Basic cross-validation functions for running classification and regression experiments using the tsml results file format.

[ENH] Cross-validation experiment functions

---

tsml_eval/_wip/forecasting/exponential_smoothing.py

setting up an area for implementing stats forecasting based on Hyndman C implementationa

[ENH] WIP area for forecasting

---

tsml_eval/segmentation/__init__.py
tsml_eval/segmentation/_bu.py
tsml_eval/segmentation/_sw.py
tsml_eval/segmentation/_swab.py
tsml_eval/segmentation/_td.py
tsml_eval/segmentation/base.py
tsml_eval/segmentation/manual_test.py

Unfinished implementations of research paper: https://ieeexplore.ieee.org/abstract/document/989531
Just using [SEG] in title short for segmentation.

[SEG] Piecewise Linear Approximation (PLA)- unfinished implementations

---

tsml_eval/estimators/clustering/__init__.py
tsml_eval/estimators/clustering/_r_clustering/__init__.py
tsml_eval/estimators/clustering/_r_clustering/_r_clustering.py
tsml_eval/estimators/clustering/_r_clustering/_r_clustering_minirocket.py

This PR implements R-clustering. It uses code from https://github.com/jorgemarcoes/R-Clustering/blob/main/R_Clustering_on_UCR_Archive.ipynb and adapts it to use aeons transformer and clusterer base class.

[ENH] Implemented r clustering

---

.github/workflows/pr_pre_commit.yml

Hopefully fix pre-commit crashes for forks

[MNT] pre-commit workflow fix

---

tsml_eval/_wip/forecasting/exponential_smoothing.py

ported etscalc and helper functions from Hyndman's forecast package (see https://github.com/robjhyndman/forecast/blob/master/src/etscalc.c) 
Haven't yet tested/compared correctness of output.

[ENH] Forecasting ETSCALC function

---

.github/workflows/scorecard.yml
pyproject.toml
tsml_eval/estimators/clustering/tests/test_r_clustering.py
tsml_eval/experiments/set_classifier.py
tsml_eval/experiments/set_clusterer.py

[MNT] Update aeon

---

tsml_eval/_wip/forecasting/exponential_smoothing.py
tsml_eval/_wip/forecasting/exponential_smoothing_comparison.py

Added script comparing output and runtime of fit_ets function with ets_calc (Nixtla's implementation)

[ENH] Added comparison code for fit_ets function

---

tsml_eval/_wip/forecasting/base.py
tsml_eval/_wip/forecasting/ets.py
tsml_eval/_wip/forecasting/example_uses.py
tsml_eval/_wip/forecasting/exponential_smoothing.py
tsml_eval/_wip/forecasting/window_base.py

first version of a BaseForecaster that works with regression. There are a lot of design issues, this is a start. Next step is to force ETS into this framework

[ENH] Base forecaster simplest version

---

tsml_eval/evaluation/multiple_estimator_evaluation.py

currently always putds accuracy as the label of the scatter, now adds correct metric

[ENH] Add argument for axis labels to plot_scatter in _figures_for_statistic

---

tsml_eval/publications/clustering/kesba/kesba.ipynb

[PUB] KESBA notebook

---

.github/workflows/issue_comment_edited.yml
.github/workflows/issue_comment_posted.yml
.github/workflows/periodic_tests.yml
.github/workflows/pr_examples.yml
.github/workflows/pr_opened.yml
.github/workflows/pr_precommit.yml
.github/workflows/pr_pytest.yml
.github/workflows/pr_typecheck.yml
.github/workflows/release.yml
.github/workflows/weekly_github_maintenace.yml
.readthedocs.yml
README.md
pyproject.toml
tsml_eval/__init__.py

UpdatePython version and bump release version

[ENH] Python 3.13 and release

---

.github/utilities/pr_welcome_edited.py
.github/workflows/issue_comment_edited.yml
.github/workflows/issue_comment_posted.yml
.github/workflows/periodic_tests.yml
.github/workflows/pr_examples.yml
.github/workflows/pr_opened.yml
.github/workflows/pr_precommit.yml
.github/workflows/pr_pytest.yml
.github/workflows/pr_typecheck.yml
.github/workflows/release.yml
.github/workflows/weekly_github_maintenance.yml

[MNT] Workflow maintenance

---

.github/utilities/pr_open_commenter.py
.github/utilities/pr_welcome_edited.py
.github/utilities/uncheck_welcome_boxes.py
.github/workflows/issue_comment_edited.yml
.github/workflows/pr_label_edited.yml

testing whether the workflows all work fine now

[MNT] Hide config options on PR comment
